'use client';

import Link from 'next/link';
import dynamic from 'next/dynamic';
import {useState} from 'react';
import {activityItems,evidenceChecks,reviewCases} from '../lib/demo-data';
import {orbitalDemo,periodMinutes,speedKmS} from '../lib/orbital-demo';
import {agentBranches,evaluateScenario,type BranchId,type ScenarioId} from '../lib/mission-workflow';
import {useWorkspace,downloadJson,financeTotals,defaultFinance,type FinanceInputs} from './workspace-state';
const EarthViewport=dynamic(()=>import('./earth-viewport').then(m=>m.EarthViewport),{ssr:false,loading:()=> <p className="wa-empty">Preparing orbital view…</p>});
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);

function Tag({children,attention=false}:{children:React.ReactNode;attention?:boolean}){return <span className={`wa-tag ${attention?'attention':''}`}>{children}</span>;}
function ToolHeader({title,children}:{title:string;children?:React.ReactNode}){return <header className="wa-panel-header"><h2>{title}</h2><div>{children}</div></header>;}

function Overview(){const s=useWorkspace();return <>
  <div className="wa-page-actions"><Link className="wa-button primary" href="/app/collision/">Open review queue ↗</Link><Link className="wa-button" href="/app/orbits/">Open orbital view</Link></div>
  <section className="wa-stats" aria-label="Mission summary"><article><span>Demo spacecraft</span><strong>08</strong><Link href="/app/satellites/">Browse registry ↗</Link></article><article><span>Priority reviews</span><strong className="wa-red">03</strong><Link href="/app/collision/">P0 / P1 cases ↗</Link></article><article><span>Supplied evidence checks</span><strong>02 <small>/ 04</small></strong><span>2 checks need attention</span></article><article><span>Assessment status</span><strong className="wa-status-text">{s.trace.length?'Ready for review':'Not run'}</strong><Link href="/app/agents/">{s.trace.length?'Inspect latest results':'Run an assessment'} ↗</Link></article></section>
  <div className="wa-overview-grid"><section className="wa-panel"><ToolHeader title="Priority cases"><Tag>Supplied snapshot</Tag></ToolHeader><div className="wa-priority-list">{reviewCases.slice(0,3).map(c=><Link key={c.id} href="/app/collision/" onClick={()=>s.setCaseId(c.id)}><Tag attention>{c.urgency}</Tag><span><strong>{c.primary}</strong><small>{c.reason}</small></span><span>{c.evidence}<b>↗</b></span></Link>)}</div><footer className="wa-panel-footer"><span>5 total cases in the review queue</span><Link href="/app/collision/">View all cases →</Link></footer></section>
  <section className="wa-panel"><ToolHeader title="Analysis tools"/><div className="wa-tool-list">{[['agents','Agent orchestrator','Audit inputs and inspect branch findings'],['finance','Financial analysis','Calculate and compare scenario exposure'],['terrain','Terrain analysis','Review footprint and exposure requirements']].map(([id,name,desc])=><Link key={id} href={`/app/${id}/`}><span><strong>{name}</strong><small>{desc}</small></span><b>↗</b></Link>)}</div></section></div>
  <section className="wa-panel"><ToolHeader title="Latest assessment"><Link className="wa-button small" href="/app/activity/">Open activity ↗</Link></ToolHeader>{s.trace.length?<div className="wa-result-summary"><Tag attention={s.runScenario==='review'}>{s.runScenario==='review'?'Analyst review required':'Evidence review'}</Tag><p>{s.trace.at(-1)?.detail}</p><small>Calculated {s.runAt} · local fixture</small></div>:<div className="wa-empty"><h3>No assessment has been run in this session.</h3><p>Choose a supplied scenario in the agent orchestrator. Its results will appear here and in Activity.</p><Link className="wa-button" href="/app/agents/">Open orchestrator</Link></div>}</section>
</>;}

function Satellites(){const s=useWorkspace();const [query,setQuery]=useState(''),[flagged,setFlagged]=useState(false);const selected=orbitalDemo.find(o=>o.id===s.selectedSat)!;const rows=orbitalDemo.filter(o=>(!flagged||o.review)&&`${o.name} ${o.id} ${o.operator} ${o.mission}`.toLowerCase().includes(query.toLowerCase()));return <>
  <div className="wa-toolbar"><label className="wa-search-field">Search spacecraft<input type="search" placeholder="Name, mission, operator or ID" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className={`wa-button ${flagged?'selected':''}`} aria-pressed={flagged} onClick={()=>setFlagged(!flagged)}>Review flagged {flagged?'✓':''}</button><Link className="wa-button primary" href="/app/orbits/">Open orbital view ↗</Link></div>
  <div className="wa-detail-grid"><section className="wa-panel"><ToolHeader title="Spacecraft registry"><span>{rows.length} / 8 objects</span></ToolHeader><div className="wa-table-scroll"><table className="wa-table"><thead><tr><th>Spacecraft</th><th>Mission</th><th>Altitude</th><th>State</th></tr></thead><tbody>{rows.map(o=><tr key={o.id} className={s.selectedSat===o.id?'selected':''}><td><button onClick={()=>s.setSelectedSat(o.id)} aria-pressed={s.selectedSat===o.id}><strong>{o.name}</strong><small>{o.id}</small></button></td><td>{o.mission}</td><td>{o.altitude} km</td><td><Tag attention={o.review}>{o.review?'Review':'Demo'}</Tag></td></tr>)}</tbody></table></div>{!rows.length&&<div className="wa-empty"><p>No matching spacecraft.</p><button className="wa-button" onClick={()=>{setQuery('');setFlagged(false);}}>Clear filters</button></div>}</section>
  <aside className="wa-panel wa-object-detail"><ToolHeader title={selected.name}><Tag attention={selected.review}>{selected.review?'Review flag':'Demo object'}</Tag></ToolHeader><div className="wa-object-symbol" aria-hidden="true"><i/><b/></div><dl className="wa-properties"><div><dt>Object ID</dt><dd>{selected.id}</dd></div><div><dt>Operator</dt><dd>{selected.operator}</dd></div><div><dt>Mission</dt><dd>{selected.mission}</dd></div><div><dt>Altitude</dt><dd>{selected.altitude} km</dd></div><div><dt>Inclination</dt><dd>{selected.inclination}°</dd></div><div><dt>Period</dt><dd>{periodMinutes(selected).toFixed(1)} min</dd></div></dl><p className="wa-note">{selected.note}</p><Link className="wa-button full" href="/app/orbits/">Locate in orbital view ↗</Link></aside></div><p className="wa-footnote">Fictional registry. Selecting a spacecraft does not assess its safety.</p>
</>;}

function Orbits(){const s=useWorkspace(),[playing,setPlaying]=useState(false),[zoom,setZoom]=useState(1);const sat=orbitalDemo.find(o=>o.id===s.selectedSat)!;return <>
  <div className="wa-toolbar"><label className="wa-select-field">Selected spacecraft<select value={s.selectedSat} onChange={e=>s.setSelectedSat(e.target.value)}>{orbitalDemo.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><button className="wa-button primary" onClick={()=>setPlaying(!playing)} aria-pressed={playing}>{playing?'Pause orbits':'Play orbits'}</button><div className="wa-button-group" role="group" aria-label="Camera zoom"><button onClick={()=>setZoom(z=>Math.max(.7,z-.1))} disabled={zoom<=.7} aria-label="Zoom out">−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(1.4,z+.1))} disabled={zoom>=1.4} aria-label="Zoom in">+</button><button onClick={()=>setZoom(1)}>Reset</button></div><Link className="wa-button" href="/app/satellites/">Registry ↗</Link></div>
  <section className="wa-orbit-tool" aria-label="Orbital inspection"><EarthViewport constellation playing={playing} zoom={zoom} selected={s.selectedSat} onSelect={s.setSelectedSat}/><aside className="wa-orbit-readout"><span>SELECTED / {sat.id}</span><h2>{sat.name}</h2><p>{sat.mission}</p><dl><div><dt>Altitude</dt><dd>{sat.altitude} km</dd></div><div><dt>Speed</dt><dd>{speedKmS(sat).toFixed(2)} km/s</dd></div></dl><Tag attention={sat.review}>{sat.review?'Review flagged':'Demo object'}</Tag></aside><span className="wa-orbit-caption">NASA mesh · custom ray tracing</span></section><p className="wa-footnote">Illustrative circular orbits at 240× time with expanded spacing. Red dots are spacecraft, not collision detections. Reduced-motion preferences stop automatic motion.</p>
</>;}

function Collision(){const s=useWorkspace(),[query,setQuery]=useState(''),[urgency,setUrgency]=useState('all'),[draft,setDraft]=useState<Record<string,string>>({}),[saved,setSaved]=useState('');const c=reviewCases.find(c=>c.id===s.caseId)??reviewCases[0];const rows=reviewCases.filter(c=>(urgency==='all'||c.urgency===urgency)&&`${c.id} ${c.primary} ${c.secondary} ${c.evidence}`.toLowerCase().includes(query.toLowerCase()));return <>
  <div className="wa-toolbar"><label className="wa-search-field">Search cases<input type="search" placeholder="Case ID, spacecraft or evidence state" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="wa-select-field">Priority<select value={urgency} onChange={e=>setUrgency(e.target.value)}><option value="all">All priorities</option>{['P0','P1','P2','P3'].map(p=><option key={p}>{p}</option>)}</select></label><Link className="wa-button primary" href="/app/agents/">Run local assessment ↗</Link></div>
  <section className="wa-panel"><ToolHeader title="Review queue"><span>{rows.length} supplied cases</span></ToolHeader><div className="wa-table-scroll"><table className="wa-table"><thead><tr><th>Priority</th><th>Case / primary object</th><th>Secondary object</th><th>Evidence</th><th>Decision time</th><th>Analyst</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className={r.id===c.id?'selected':''}><td><Tag attention={r.urgency==='P0'||r.urgency==='P1'}>{r.urgency}</Tag></td><td><button onClick={()=>{s.setCaseId(r.id);setSaved('');}}><strong>{r.primary}</strong><small>{r.id}</small></button></td><td>{r.secondary}</td><td>{r.evidence}</td><td>{r.slack}</td><td>{r.analyst}</td></tr>)}</tbody></table></div>{!rows.length&&<p className="wa-empty">No cases match your search.</p>}</section>
  <section className="wa-panel wa-case-inspector"><ToolHeader title={`${c.id} / Evidence snapshot`}><button className="wa-button small" onClick={()=>downloadJson(`${c.id}.json`,{mode:'supplied synthetic snapshot',case:c,note:s.notes[c.id]??''})}>Export case ↓</button></ToolHeader><div className="wa-case-body"><article><Tag attention>{c.evidence}</Tag><h3>{c.primary} ↔ {c.secondary}</h3><p>{c.reason}.</p><dl className="wa-properties"><div><dt>Supplied probability</dt><dd>{c.pc}</dd></div><div><dt>Review deadline</dt><dd>{c.deadline}</dd></div><div><dt>Stage</dt><dd>{c.stage}</dd></div></dl>{c.id==='OT-0911-014'&&<ul className="wa-checks">{evidenceChecks.map(e=><li key={e.label}><span className={e.state==='pass'?'':'wa-red'}>{e.state==='pass'?'✓':'!'}</span><div><strong>{e.label}</strong><p>{e.detail}</p></div></li>)}</ul>}</article><form onSubmit={e=>{e.preventDefault();s.setNotes(n=>({...n,[c.id]:draft[c.id]??s.notes[c.id]??''}));setSaved(c.id);}}><label className="wa-field">Analyst note<textarea value={draft[c.id]??s.notes[c.id]??''} onChange={e=>{setDraft(d=>({...d,[c.id]:e.target.value}));setSaved('');}} placeholder="Record an evidence-linked observation…" rows={6}/></label><button className="wa-button primary" type="submit">Save note</button><p className="wa-footnote" role="status">{saved===c.id?'Note saved for this tab session.':'Notes remain in this tab until refresh.'}</p><Link href="/app/finance/" className="wa-inline-link">Open financial analysis ↗</Link></form></div></section>
</>;}

function Agents(){const s=useWorkspace(),[branch,setBranch]=useState<BranchId>('collision');const b=agentBranches.find(b=>b.id===branch)!;const event=s.trace.find(e=>e.branch===branch);return <>
  <div className="wa-toolbar"><label className="wa-select-field">Input scenario<select value={s.scenario} onChange={e=>s.setScenario(e.target.value as ScenarioId)}><option value="review">Close approach / incomplete evidence</option><option value="monitor">Wider separation / recent epoch</option></select></label><button className="wa-button primary" onClick={s.run}>Run assessment</button><button className="wa-button" disabled={!s.trace.length} onClick={()=>downloadJson('orbit-assessment.json',{mode:'local deterministic demonstration',scenario:s.runScenario,calculatedAt:s.runAt,events:s.trace})}>Export trace ↓</button><Link className="wa-button" href="/app/activity/">Activity ↗</Link></div>
  <div className="wa-inline-status" role="status"><span className="wa-status-dot"/>{s.trace.length?`6 branch results recorded for ${s.runScenario==='review'?'Close approach':'Wider separation'}. ${s.scenario!==s.runScenario?'Inputs changed — run again to update results.':'Ready for analyst review.'}`:'Select a scenario and run the deterministic assessment. No live agent services are connected.'}</div>
  <section className="wa-agent-root"><span className="wa-root-icon">⌘</span><div><h2>Assessment orchestrator</h2><p>Input audit → collision → terrain gate → financial exposure → judge</p></div><Tag>{s.trace.length?'Results available':'Ready'}</Tag></section>
  <div className="wa-agent-grid"><nav className="wa-branch-list" aria-label="Agent branches">{agentBranches.map(item=>{const e=s.trace.find(e=>e.branch===item.id);return <button key={item.id} className={branch===item.id?'selected':''} aria-pressed={branch===item.id} onClick={()=>setBranch(item.id)}><span>{item.code}</span><div><strong>{item.name}</strong><small>{item.specialists.length} specialist nodes</small></div><small>{e?e.state:'Not run'}</small></button>;})}</nav><section className="wa-panel"><ToolHeader title={b.name}><Tag attention={event?.state==='attention'}>{event?.state??'Not run'}</Tag></ToolHeader><p className="wa-branch-description">{b.purpose}</p><div className="wa-node-list">{b.specialists.map((node,i)=><details key={node.name}><summary><span>{String(i+1).padStart(2,'0')}</span><strong>{node.name}</strong><b>+</b></summary><dl><dt>Input</dt><dd>{node.input}</dd><dt>Output</dt><dd>{node.output}</dd><dt>Execution</dt><dd>Proposed specialist; current local run records a branch-level result.</dd></dl></details>)}</div><div className="wa-branch-result"><span>BRANCH FINDING</span><p>{event?.detail??'No result yet. Run an assessment to inspect this branch’s finding.'}</p></div><footer className="wa-panel-footer"><span>Evidence-linked output · human decision required</span>{branch==='finance'?<Link href="/app/finance/">Open finance tool ↗</Link>:branch==='terrain'?<Link href="/app/terrain/">Open terrain tool ↗</Link>:<Link href="/app/collision/">Open review queue ↗</Link>}</footer></section></div>
  {s.runScenario==='review'&&s.trace.length>0&&!s.acknowledged&&<aside className="wa-review-alert" role="alert"><span>!</span><div><strong>Close-approach fixture requires review</strong><p>120 m at T+300 s in the linear model. Collision probability is unavailable without covariance.</p></div><button className="wa-button" onClick={()=>s.setAcknowledged(true)}>Acknowledge</button></aside>}
  <p className="wa-footnote">19 specialist definitions describe the intended architecture. Calculations are local; there is no simulated waiting period, LLM service, or flight command.</p>
</>;}

function Finance(){const s=useWorkspace(),[compare,setCompare]=useState(false),[error,setError]=useState('');const input=s.finance,result=s.financeResult?financeTotals(s.financeResult):null;const changed=!!s.financeResult&&JSON.stringify(input)!==JSON.stringify(s.financeResult);const fields:[keyof FinanceInputs,string,string][]=[['replacement','Replacement cost','USD'],['dailyRevenue','Daily service revenue','USD / day'],['days','Loss scenario downtime','days'],['responseCost','Response cost','USD'],['responseDays','Response scenario downtime','days']];return <>
  <div className="wa-page-actions"><Link className="wa-button" href="/app/agents/">Agent orchestrator ↗</Link><button className="wa-button" onClick={()=>{s.setFinance({...defaultFinance});s.setFinanceResult(null);setCompare(false);setError('');}}>Reset assumptions</button><button className="wa-button" disabled={!result} onClick={()=>downloadJson('orbit-financial-comparison.json',{mode:'conditional demonstration, not realized savings',assumptions:s.financeResult,results:result,excluded:['collision probability','insurance recovery','ground exposure']})}>Export calculation ↓</button></div>
  <div className="wa-finance-grid"><section className="wa-panel"><ToolHeader title="Scenario assumptions"><Tag>Editable / USD</Tag></ToolHeader><form className="wa-finance-form" onSubmit={e=>{e.preventDefault();try{financeTotals(input);s.setFinanceResult({...input});setError('');}catch(e){setError((e as Error).message);}}}>{fields.map(([key,label,unit])=><label key={key} className="wa-field">{label}<div className="wa-number-input"><input type="number" required min="0" max="1000000000000" step="any" value={Number.isNaN(input[key])?'':input[key]} onChange={e=>s.setFinance(v=>({...v,[key]:e.target.value===''?NaN:Number(e.target.value)}))}/><span>{unit}</span></div></label>)}{error&&<p className="wa-error" role="alert">{error}</p>}<button className="wa-button primary" type="submit">Calculate exposure</button><p className="wa-footnote">Assumptions stay in this tab. Changes take effect when you calculate.</p></form></section>
  <section className="wa-panel wa-financial-results"><ToolHeader title="Financial exposure"><Tag>{result?'Calculated locally':'Awaiting calculation'}</Tag></ToolHeader>{result&&s.financeResult?<><div className="wa-finance-total"><span>Conditional loss</span><strong>{money(result.conditionalLoss)}</strong><small>Replacement + service interruption</small></div><dl className="wa-cost-breakdown"><div><dt>Replacement cost</dt><dd>{money(s.financeResult.replacement)}</dd></div><div><dt>Service interruption ({s.financeResult.days} days)</dt><dd>{money(result.service)}</dd></div><div><dt>Insurance recovery</dt><dd>Not supplied</dd></div><div><dt>Ground exposure</dt><dd>Not supplied</dd></div></dl>{changed&&<p className="wa-stale" role="status">Assumptions changed. Calculate again to update these results.</p>}<button className="wa-button full" aria-expanded={compare} onClick={()=>setCompare(!compare)}>{compare?'Hide response comparison':'Compare response scenario'} {compare?'−':'+'}</button>{compare&&<div className="wa-response-comparison"><h3>Conditional scenario comparison</h3><dl><div><dt>Loss scenario</dt><dd>{money(result.conditionalLoss)}</dd></div><div><dt>Response scenario</dt><dd>{money(result.responseScenario)}</dd></div><div><dt>Difference</dt><dd>{money(result.difference)}</dd></div></dl><p>Response scenario assumes the spacecraft is retained and service resumes after {s.financeResult.responseDays} days, plus {money(s.financeResult.responseCost)} response cost. Feasibility and success probability have not been assessed.</p><strong>This difference is not money actually saved.</strong></div>}</>:<div className="wa-empty wa-finance-empty"><span className="wa-finance-symbol">ƒ</span><h3>Start with the assumptions.</h3><p>Set replacement, service and response costs, then calculate an explicit loss scenario.</p></div>}</section></div><p className="wa-footnote">No probability weighting, insurance recovery or ground-damage estimate. This is a conditional comparison, not a financial forecast or maneuver recommendation.</p>
</>;}

function Terrain(){const required=[['Reentry footprint','Georeferenced corridor or polygon, epoch and model provenance'],['Land-cover & elevation','Source version, coordinate reference system and resolution'],['Population & asset exposure','Coverage date, units and aggregation rules'],['Object & breakup assumptions','Object mass, survivability model and uncertainty bounds']];return <><div className="wa-page-actions"><button className="wa-button primary" onClick={()=>downloadJson('terrain-data-request.json',{type:'terrain-input-request',mode:'demonstration',status:'withheld',required:required.map(([name,description])=>({name,description}))})}>Export data request ↓</button><Link className="wa-button" href="/app/finance/">Financial analysis ↗</Link></div><aside className="wa-inline-status"><span className="wa-status-dot"/>Assessment withheld. A conjunction warning alone does not provide a reentry footprint.</aside><section className="wa-panel"><ToolHeader title="Input readiness"><Tag attention>0 / 4 supplied</Tag></ToolHeader><div className="wa-requirements">{required.map(([name,description],i)=><article key={name}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{name}</h3><p>{description}</p></div><Tag>Missing</Tag></article>)}</div></section><section className="wa-panel"><ToolHeader title="Assessment sequence"/><ol className="wa-terrain-steps"><li><strong>Validate footprint</strong><span>Confirm epoch, frame and applicability.</span></li><li><strong>Intersect terrain</strong><span>Classify the supplied geographic corridor.</span></li><li><strong>Aggregate exposure</strong><span>Report ranges with source coverage.</span></li><li><strong>Pass to finance</strong><span>Keep ground and spacecraft losses separate.</span></li></ol></section><p className="wa-footnote">The TerraSight integration remains an input gate. No crash destination or ground-damage amount is invented.</p></>;}

function Activity(){const s=useWorkspace(),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState('');const local=s.trace.map(e=>({id:e.id,time:s.runAt??'',title:e.title,detail:e.detail,kind:e.state==='attention'?'alert':'calc',source:'Local assessment'}));const all=[...local.toReversed(),...activityItems.map((e,i)=>({...e,id:`fixture-${i}`,source:'Supplied historical fixture'}))];const rows=all.filter(e=>(filter==='all'||e.kind===filter)&&`${e.title} ${e.detail} ${e.source}`.toLowerCase().includes(query.toLowerCase()));const detail=all.find(e=>e.id===selected);return <><div className="wa-toolbar"><label className="wa-search-field">Search events<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Finding, source or event name"/></label><label className="wa-select-field">Event type<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All events</option><option value="alert">Attention</option><option value="calc">Calculations</option><option value="data">Imports</option></select></label><button className="wa-button" onClick={()=>downloadJson('orbit-activity.json',{mode:'demo',events:rows})}>Export view ↓</button></div><section className="wa-panel"><ToolHeader title="Event ledger"><span>{rows.length} events</span></ToolHeader><div className="wa-events">{rows.map(e=><button key={e.id} onClick={()=>setSelected(selected===e.id?'':e.id)} aria-expanded={selected===e.id}><span className={`wa-event-dot ${e.kind==='alert'?'attention':''}`}/><span><strong>{e.title}</strong><small>{e.source}</small></span><time>{e.source==='Local assessment'?'This session':e.time}</time><span>{e.kind}</span><b>{selected===e.id?'−':'+'}</b></button>)}</div>{!rows.length&&<div className="wa-empty"><p>No matching events.</p><button className="wa-button" onClick={()=>{setQuery('');setFilter('all');}}>Clear filters</button></div>}</section>{detail&&<section className="wa-panel"><ToolHeader title={detail.title}><Tag>{detail.source}</Tag></ToolHeader><div className="wa-event-detail"><p>{detail.detail}</p><code>{detail.id}</code></div></section>}</>;}

function Methods(){return <section className="wa-panel wa-methods"><ToolHeader title="What this workspace does"/><article><h3>Local, reproducible demonstration</h3><p>Collision geometry uses a short-horizon constant-relative-velocity model and the existing engine’s Vec3 math. Supplied close-approach and wider-separation fixtures are available in the orchestrator. A 500 m demonstration threshold requests review; it is not a collision determination.</p><h3>Ray tracing and orbit display</h3><p>The NASA Earth mesh is ray traced through the custom engine’s packed BVH. Direct sunlight, normal mapping and an atmospheric shell shade the model. Circular satellite paths are fictional, accelerated and visually expanded. The view is not a live telemetry feed.</p><h3>Financial and terrain limits</h3><p>Financial results are conditional scenario arithmetic. No collision probability, insurance payout or realized savings are inferred. Terrain calculations remain withheld without a separately supplied footprint and exposure data.</p><h3>Agent architecture</h3><p>Five branches contain 19 proposed specialists. The current assessment computes branch findings locally; no ADK/Groq service is called. The router, specialist and judge pattern is adapted from <a href="https://github.com/Adhirajsingh2507/Error-404-Not-Found" target="_blank" rel="noreferrer">your Finora repository ↗</a>.</p><h3>Session data</h3><p>App navigation preserves calculation results, selected objects and saved notes in memory. Refreshing resets the demo. Export a result or note before leaving if you need a copy. No login, cloud persistence or flight command is connected.</p></article></section>;}

export function WorkspacePage({view}:{view:string}){switch(view){case'satellites':return <Satellites/>;case'orbits':return <Orbits/>;case'collision':return <Collision/>;case'agents':return <Agents/>;case'finance':return <Finance/>;case'terrain':return <Terrain/>;case'activity':return <Activity/>;case'methods':return <Methods/>;default:return <Overview/>;}}
